---
- name: Install Nexus Repository
  hosts: all
  become: true

  roles:
    - role: ansible-ThoTeam.nexus3-oss

  vars:
    nexus_version: "3.79.1"
    nexus_admin_password: "MyStrongPassword"
    nexus_blob_stores:
      - name: default
        type: File
        path: default
    nexus_repositories:
      - name: "maven-public"
        type: "maven"
        recipe: "maven2"
        online: true
        storage:
          blob_store_name: "default"
          strict_content_type_validation: false
